name: Generate Snake Animation

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Executa diariamente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          color_snake: "#ffffff" # Cobra branca
          color_dots: "#999999" # Pontos cinza claro
          color_background: "#0d1117" # Fundo escuro (preto ou próximo)

      - name: Deploy Snake
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          github_token: ${{ secrets.GITHUB_TOKEN }}

