name: Gerar Snake Animation

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Executa todos os dias

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Instalação de Dependências
        run: npm install

      - name: Gerar Snake Animation no Modo Dark
        uses: Platane/snk@v2
        with:
          github_user_name: 'OtavioDayrots' # Seu nome de usuário GitHub
          svg_style: 'dark' # Modo Dark

      - name: Publicar no Branch de Output
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
